-- Streams and Tasks demo: schema, employee table, and scheduled cleanup task
-- Co-authored with CoCo




CREATE OR REPLACE TABLE VITECH_DEV.BRONZE.EMPLOYEE (
    EID INT,
    NAME VARCHAR(100),
    STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO EMPLOYEE (EID, NAME, STATUS) VALUES (11, ' Sharma', 'InActive');
INSERT INTO EMPLOYEE (EID, NAME, STATUS) VALUES (12, 'Priya Patel', 'InActive');
INSERT INTO EMPLOYEE (EID, NAME, STATUS) VALUES (13, 'Amit Kumar', 'Inactive');
INSERT INTO EMPLOYEE (EID, NAME, STATUS) VALUES (4, 'Sneha Reddy', 'Active');
INSERT INTO EMPLOYEE (EID, NAME, STATUS) VALUES (5, 'Vikram Singh', 'On Leave');



select * from VITECH_DEV.BRONZE.EMPLOYEE;




CREATE OR REPLACE TASK CLEANUP_INACTIVE_EMPLOYEES
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '2 MINUTE'      ---- SCHEDULE =( USING CRON */2 * * * * UTC)
AS
  DELETE FROM VITECH_DEV.BRONZE.EMPLOYEE
  WHERE UPPER(STATUS) = 'INACTIVE';


  show tasks ;

ALTER TASK CLEANUP_INACTIVE_EMPLOYEES RESUME;


ALTER TASK CLEANUP_INACTIVE_EMPLOYEES RESUME;


---------------------------------

CREATE OR REPLACE STAGE OMS_DEV.PUBLIC.ORDERS_STAGE
  URL = 's3://bucketsnowflakes3/';

LIST @OMS_DEV.PUBLIC.ORDERS_STAGE 




CREATE OR REPLACE TABLE VITECH_DEV.Bronze.ORDERS_V1 (
  ORDER_ID STRING,
  AMOUNT STRING,
  PROFIT STRING,
  QUANTITY STRING,
  CATEGORY STRING,
  SUB_CATEGORY STRING
);



SELECT COUNT(*) AS TOTAL_RECORDS FROM VITECH_DEV.Bronze.ORDERS_V1;



CREATE OR REPLACE TASK load_data_task
  WAREHOUSE = COMPUTE_WH
  SCHEDULE ='USING CRON */2 * * * * UTC'  
AS 
COPY INTO VITECH_DEV.Bronze.ORDERS_V1
FROM @OMS_DEV.PUBLIC.ORDERS_STAGE
PATTERN = '.*OrderDetails.*'
FILE_FORMAT = (TYPE = CSV, SKIP_HEADER = 1, FIELD_DELIMITER = ',')
FORCE=TRUE ;

SELECT * FROM VITECH_DEV.Bronze.ORDERS_V1;

show tasks ;

alter task load_data_task  suspend ;



CREATE OR REPLACE STREAM orders_STREAM ON TABLE VITECH_DEV.Bronze.ORDERS_V1;



select * from orders_STREAM;

-----------------------------------------------



CREATE OR REPLACE TABLE VITECH_DEV.BRONZE.EMP (
    EID INT,
    NAME VARCHAR(100),
    STATUS VARCHAR(50),
    city string ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


CREATE SCHEMA  VITECH_DEV.SILVER;

CREATE SCHEMA  VITECH_DEV.GOLD;

CREATE OR REPLACE TABLE VITECH_DEV.BRONZE.EMP (
    EID INT,
    NAME VARCHAR(100),
    STATUS VARCHAR(50),
    CITY STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO VITECH_DEV.BRONZE.EMP (EID, NAME, STATUS, CITY) VALUES (1, 'Rahul Sharma', 'Active', 'Mumbai');
INSERT INTO VITECH_DEV.BRONZE.EMP (EID, NAME, STATUS, CITY) VALUES (2, 'Priya Patel', 'Inactive', 'Delhi');
INSERT INTO VITECH_DEV.BRONZE.EMP (EID, NAME, STATUS, CITY) VALUES (3, 'Amit Kumar', 'Active', 'Bangalore');
INSERT INTO VITECH_DEV.BRONZE.EMP (EID, NAME, STATUS, CITY) VALUES (4, 'Sneha Reddy', 'On Leave', 'Hyderabad');
INSERT INTO VITECH_DEV.BRONZE.EMP (EID, NAME, STATUS, CITY) VALUES (5, 'Vikram Singh', 'Active', 'Pune');


CREATE OR REPLACE STREAM EMP_STREAM ON TABLE VITECH_DEV.BRONZE.EMP;



select * from EMP_STREAM ;

select * from VITECH_DEV.BRONZE.EMP;


select * from VITECH_DEV.silver.EMP_final ;



select * from VITECH_DEV.silver.EMP_final ;


select * from VITECH_DEV.bronze.EMP;


---merge logic 

CREATE OR REPLACE TASK EMP_MERGE_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('EMP_STREAM')
AS
  MERGE INTO VITECH_DEV.SILVER.EMP_FINAL AS TGT
  USING (
    SELECT EID, NAME, STATUS, CITY, CREATED_AT
    FROM EMP_STREAM
    WHERE METADATA$ACTION = 'INSERT'
  ) AS SRC
  ON TGT.EID = SRC.EID
  WHEN MATCHED THEN
    UPDATE SET
      TGT.NAME = SRC.NAME,
      TGT.STATUS = SRC.STATUS,
      TGT.CITY = SRC.CITY,
      TGT.CREATED_AT = SRC.CREATED_AT
  WHEN NOT MATCHED THEN
    INSERT (EID, NAME, STATUS, CITY, CREATED_AT)
    VALUES (SRC.EID, SRC.NAME, SRC.STATUS, SRC.CITY, SRC.CREATED_AT);


    

ALTER TASK EMP_MERGE_TASK RESUME;




CREATE OR REPLACE TABLE VITECH_DEV.silver.EMP_final (
    EID INT,
    NAME VARCHAR(100),
    STA